### ISSUE TITLE
Repo needs a proper readme and a license

### ISSUE THREAD

**Issue by ManlyMarco** [IllusionMods/Stiletto#14]
Can be either GPLv3 or WTFPL.

**Comment by Splendide-Imaginarius** [comment]
I'm okay with licensing my contributions under whatever FSF-approved license you prefer.

**Comment by Splendide-Imaginarius** [comment]
What info should be included in the README?

**Comment by ManlyMarco** [comment]
Description, installation, credits, how to use, and info for zipmod makers, I suppose. You can copy parts from other repo like https://github.com/ManlyMarco/QuickAccessBox

**Comment by ManlyMarco** [comment]
@Splendide-Imaginarius Any updates? I tried using the plugin and all sliders except shear don't appear to do anything, it's not intuitive to use and would benefit from either instructions in the interface or in the readme.

**Comment by Cleep2** [comment]
Would be nice to also inform that the heels .txt config files path has changed. People need to migrate their already existing files to the new location if they had some in the old BepinEx/Stiletto folder.

**Comment by ManlyMarco** [comment]
> Would be nice to also inform that the heels .txt config files path has changed. People need to migrate their already existing files to the new location if they had some in the old BepinEx/Stiletto folder.

Sounds like it should be done automatically.

**Comment by Splendide-Imaginarius** [comment]
@ManlyMarco Sorry I missed your ping, I was away for the holidays. Looks like @Cleep2 got the Readme done before I could get to it (and they did an excellent job, far better than I would have done, so thanks!).
