### ISSUE TITLE
[KK] Stiletto doesn't work!

### ISSUE THREAD

**Issue by llzzzzll** [IllusionMods/Stiletto#4]
HF Patch 3.17

Stiletto doesn't work!

[Info   :   BepInEx] Loading [Stiletto 1.3]
[Warning:  HarmonyX] System.Void Stiletto.Stiletto.ChaFileStatus_set_shoesTypeHook(ChaFileStatus) - MethodType.Getter and MethodType.Setter should be used instead adding get_ and set_ to property names

**Comment by ManlyMarco** [comment]
What exactly is the issue? Does the maker UI work?

**Comment by llzzzzll** [comment]
> What exactly is the issue? Does the maker UI work?

@ManlyMarco 
![mmexport1657170284319](https://user-images.githubusercontent.com/1097123/177695688-ca68523c-e004-45fe-b397-d60cf71b77c1.png)

As pic you can see.
Stiletto has data. But nothing changed.

Also I updated mods by KKManager to the newest.

Update↓
One more thing! I will check my KK md5 to see is it a problem caused by game file data loss.

Update2↓
I have checked the KK file and it is ok.
Stiletto doesn't work.
At the same time KK_ViewpointSwitching.dll can not work.

**Comment by llzzzzll** [comment]
HF 3.14 supports Stiletto.
3.15/3.16/3.17 doesn't support Stiletto.

**Comment by ManlyMarco** [comment]
Please send your output_log file from game directory after trying to use high heels on a character.
