### ISSUE TITLE
KK: "Save Preset" button missing following refactor

### ISSUE THREAD

**Issue by Splendide-Imaginarius** [IllusionMods/Stiletto#5]
The "Save Preset" button seems to have been removed from KK Stiletto following a GUI refactor. It's not clear to me how saving is supposed to work now. I don't see any functions that call `SaveHeelFile` in `master`.

If this is unintentional and is just a result of a half-finished refactor, I might be up for contributing a PR to fix this. But I figured I should ask first, to see if I've missed something.

**Comment by ManlyMarco** [comment]
Most likely it's unintentional, feel free to submit a PR.

**Comment by Splendide-Imaginarius** [comment]
I made a patch today, but I also just realized that there's a fork of this repo ( https://github.com/JiarongGu/Stiletto by @JiarongGu ) which seems to already have a fix, along with some other fixes/enhancements. I haven't tested that fork yet; will try to do so in the next week or so. If that fork actually works well, might be worth considering merging their changes into this repo. (So, please hold off on the fix I made until I've had a chance to test that fork.)

**Comment by Splendide-Imaginarius** [comment]
> I haven't tested that fork yet; will try to do so in the next week or so.

Just did about an hour of testing; @JiarongGu's fork seems reasonably good. I ran into a couple of bugs, but each of them was fixable with a one-line patch. I'll continue testing, but initial impression is positive, and I suspect that my own patch can be discarded.

**Comment by ManlyMarco** [comment]
Oh, nice. I'll look into merging it if you think it's good. Can you submit the fixes you mentioned after I merge it?

**Comment by Splendide-Imaginarius** [comment]
Yes, I can submit the fixes I made (along with a couple of other feature improvements I made on top of v1.4, once I rebase them to work fine with that fork). I'm not quite done testing their fork, but will hopefully be done testing it in a few days. (Though I'm quite certain you have a better understanding of the KK code ecosystem than I do, so your review probably matters more than mine.)

**Comment by ManlyMarco** [comment]
I don't use Stiletto personally so I possibly wouldn't know a bug if I saw one :)
